[versions]
agp = "8.2.0"
dexKit = "2.0.0"
ezXHelper = "2.0.8"
xposed-api = "82"
kotlin = "1.9.22"
hiddenapibypass = "4.3"

[libraries]
dexKit = { module = "org.luckypray:dexkit", version.ref = "dexKit" }
ezXHelper = { module = "com.github.kyuubiran:EzXHelper", version.ref = "ezXHelper" }
xposed-api = { module = "de.robv.android.xposed:api", version.ref = "xposed-api" }
hiddenapibypass = { module = "org.lsposed.hiddenapibypass:hiddenapibypass", version.ref = "hiddenapibypass" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
